### ISSUE TITLE
Verify impact of fast-jwt@v2 on this package

### ISSUE THREAD

**Issue by simoneb** [nearform/fastify-auth0-verify#250]
We have a pending release to do which, among other things, includes the v2 major of fast-jwt.

Let's figure out what impact that has on this package and plan the next release accordingly.

See https://github.com/nearform/fastify-auth0-verify/issues/243

**Comment by marco-ippolito** [comment]
The major release of fast-jwt doesn't not have any impact on this package because `fastify-auth0-verify` does not  use the internal `fast-jwt` caching which has to be explicitly enabled with the field `cache` [otherwise disabled](https://github.com/nearform/fast-jwt#createVerifier).
https://github.com/nearform/fastify-auth0-verify/blob/c2f52148c25b88cbd1f74aca5e91a742b2072ce7/index.js#L30-L78

**Comment by simoneb** [comment]
Interesting find. Any thoughts on why caching is not being used? Would it be worth considering to enable it?

**Comment by marco-ippolito** [comment]
At first glance I think it's because this plugin has already it's own cache so probably it is not needed but it requires further investigation to understand what is cached and what is not.

**Comment by simoneb** [comment]
Let's have a look, it may be simply the way things turned out to be over time but since we changed the caching mechanism in fast-jwt it's worth looking into whether we can improve things

**Comment by marco-ippolito** [comment]
There are no breaking changes with the latest major release of `fast-jwt`.
The `fast-jwt`  native cache and the  new option fields introduced with the latest release can already be used in this packaged as explained by https://github.com/nearform/fastify-auth0-verify/pull/252
